# Generated by Django 5.1.1 on 2024-10-19 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('transactions', '0020_alter_billing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='payment',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
